version: '3.8'

services:
  # Bitcoin Market Intelligence API
  bitcoin-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: bitcoin-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_WHITELIST=*
      - TZ=America/Sao_Paulo
    volumes:
      - ./logs:/app/logs
      - /dev/shm:/dev/shm  # Compartilha memória compartilhada para Chrome
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/v1/bitcoin/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bitcoin-network
    deploy:
      resources:
        limits:
          memory: 400M  # Limite para t2.micro
          cpus: '0.5'
        reservations:
          memory: 200M
          cpus: '0.25'

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: bitcoin-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      bitcoin-api:
        condition: service_healthy
    networks:
      - bitcoin-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  logs:
    driver: local
  nginx-logs:
    driver: local

networks:
  bitcoin-network:
    driver: bridge
    name: bitcoin-network 